let objects = 
[ {location: [8,16], imgSrc: require('../resources/images/taco.png'), type: 'taco', style: {height: '1rem'}, interact: {remove: true}},
{location: [15,4], imgSrc: require('../resources/images/taco.png'), type: 'taco', style: {height: '1rem'}, interact: {remove: true}},
{location: [9,7], imgSrc: require('../resources/images/taco.png'), type: 'taco', style: {height: '1rem'}, interact: {remove: true}},
 {location: [13,14], imgSrc: require('../resources/images/tree.gif'), type: 'taco', style: {height: '2.5rem'}, interact: {remove: true}},
	{location: [10,2], imgSrc: require('../resources/images/tree.gif'), type: 'taco', style: {height: '2.5rem'}, interact: {remove: true}},
  {location: [5,17], imgSrc: require('../resources/images/tree.gif'), type: 'taco', style: {height: '2.5rem'}, interact: {remove: true}},
 {location: [6,4], imgSrc: require('../resources/images/cactus.png'), type: 'cactus', style: {height: '3rem'}, interact: {remove: true}},
  {location: [10,10], imgSrc: require('../resources/images/animations/Asenora.gif'), type: 'Senora' , count : 1, style: {height: '2rem'}, interact: {remove: true}},
   {location: [3,20], imgSrc: require('../resources/images/wall.png'), type: 'wall', style: {height: '1.2rem'}, interact: {remove: true}},
    {location: [3,19], imgSrc: require('../resources/images/wall.png'), type: 'wall', style: {height: '1.2rem'}, interact: {remove: true}},
     {location: [3,18], imgSrc: require('../resources/images/wall.png'), type: 'wall', style: {height: '1.2rem'}, interact: {remove: true}},
      {location: [3,17], imgSrc: require('../resources/images/wall.png'), type: 'wall', style: {height: '1.2rem'}, interact: {remove: true}},
       {location: [3,15], imgSrc: require('../resources/images/wall.png'), type: 'wall', style: {height: '1.2rem'}, interact: {remove: true}},
        {location: [3,14], imgSrc: require('../resources/images/wall.png'), type: 'wall', style: {height: '1.2rem'}, interact: {remove: true}},
         {location: [3,13], imgSrc: require('../resources/images/wall.png'), type: 'wall', style: {height: '1.2rem'}, interact: {remove: true}},
          {location: [3,12], imgSrc: require('../resources/images/wall.png'), type: 'wall', style: {height: '1.2rem'}, interact: {remove: true}},
           {location: [3,11], imgSrc: require('../resources/images/wall.png'), type: 'wall', style: {height: '1.2rem'}, interact: {remove: true}},
            {location: [3,9], imgSrc: require('../resources/images/wall.png'), type: 'wall', style: {height: '1.2rem'}, interact: {remove: true}},
             {location: [3,8], imgSrc: require('../resources/images/wall.png'), type: 'wall', style: {height: '1.2rem'}, interact: {remove: true}},
              {location: [3,7], imgSrc: require('../resources/images/wall.png'), type: 'wall', style: {height: '1.2rem'}, interact: {remove: true}},
               {location: [3,6], imgSrc: require('../resources/images/wall.png'), type: 'wall', style: {height: '1.2rem'}, interact: {remove: true}},
                {location: [3,5], imgSrc: require('../resources/images/wall.png'), type: 'wall', style: {height: '1.2rem'}, interact: {remove: true}},
                 {location: [3,3], imgSrc: require('../resources/images/wall.png'), type: 'wall', style: {height: '1.2rem'}, interact: {remove: true}},
                  {location: [3,2], imgSrc: require('../resources/images/wall.png'), type: 'wall', style: {height: '1.2rem'}, interact: {remove: true}},
                   {location: [3,1], imgSrc: require('../resources/images/wall.png'), type: 'wall', style: {height: '1.2rem'}, interact: {remove: true}},
                    {location: [3,0], imgSrc: require('../resources/images/wall.png'), type: 'wall', style: {height: '1.2rem'}, interact: {remove: true}},

  {location: [17,1], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid1' , count : 2 , style: {height: '2rem'}, interact: {remove: true}} , 
  {location: [17,3], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid8' , count : 2 , style: {height: '2rem'}, interact: {remove: true}} , 
  {location: [17,5], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid3' , count : 2 , style: {height: '2rem'}, interact: {remove: true}} , 
  {location: [17,7], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid4' , count : 3 , style: {height: '2rem'}, interact: {remove: true}} , 
  {location: [17,9], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid2' , count : 3 , style: {height: '2rem'}, interact: {remove: true}} , 
  {location: [17,11], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid5' , count : 2 , style: {height: '2rem'}, interact: {remove: true}} , 
  {location: [17,13], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid2' , count : 2 , style: {height: '2rem'}, interact: {remove: true}} , 
  {location: [17,15], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid6' , count : 2 , style: {height: '2rem'}, interact: {remove: true}} , 
  {location: [17,17], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid4' , count : 3 , style: {height: '2rem'}, interact: {remove: true}} , 
  {location: [17,19], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid7' , count : 3 , style: {height: '2rem'}, interact: {remove: true}} , 

  {location: [18,2], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid8' , count : 5 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [18,4], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid4' , count : 4 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [18,6], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid3' , count : 5 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [18,8], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid4' , count : 3 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [18,10], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid7' , count : 1 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [18,12], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid2' , count : 5 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [18,14], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid5' , count : 4 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [18,16], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid1' , count : 1 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [18,18], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid2' , count : 5 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [18,20], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid6' , count : 4 , style: {height: '2rem'}, interact: {remove: true}} , 

  {location: [19,1], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid2' , count : 2 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [19,3], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid1' , count : 5 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [19,5], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid4' , count : 3 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [19,7], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid3' , count : 5 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [19,9], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid6' , count : 5 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [19,11], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid2' , count : 2 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [19,13], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid5' , count : 5 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [19,15], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid7' , count : 5 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [19,17], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid4' , count : 3 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [19,19], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid8' , count : 5 , style: {height: '2rem'}, interact: {remove: true}} ,

  {location: [20,2], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid3' , count : 5 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [20,4], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid5' , count : 4 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [20,6], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid6' , count : 5 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [20,8], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid4' , count : 3 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [20,10], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid2' , count : 5 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [20,12], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid8' , count : 5 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [20,14], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid7' , count : 4 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [20,16], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid1' , count : 1 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [20,18], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid6' , count : 5 , style: {height: '2rem'}, interact: {remove: true}} ,
  {location: [20,20], imgSrc: require('../resources/images/animations/blank.png'), type: 'mexican',nombre: 'kid5' , count : 4 , style: {height: '2rem'}, interact: {remove: true}} , 

 ]


export default objects