import React from 'react'
import '../../reset.css'
import './square.css'



class Square extends React.PureComponent {
	constructor(props) {
		super(props)    
		this.position = this.props.position;																															// a 2d array like [0,0] generated by the Board components render loop 
		this.handleClick = this.handleClick.bind(this)
		this.migrate = this.migrate.bind(this)
		this.followUp = false
	}

	handleClick(e) {
		if(!this.followUp) {
			this.props.handleClick(this.props.position[0],this.props.position[1])													// this passes the Game component's playMove method the value of the caller which mutates this.props.playerBoard
			this.followUp = true
			setTimeout(()=>{this.followUp = false},400)
		}
	}

	migrate(position){
		setTimeout (() => {
		this.props.migrate(position)
	  },this.position[0]*25-50)
	}

	getObject() {
		let rev = ''
		let object = this.props.board.objectBoard[this.position[0]][this.position[1]]
		if (object) {
			if(object.type==='mexican') {
				if(this.position[0]%2===1){ rev = 'reverse'}
				return <img src={object.imgSrc} style={object.style} onLoad={this.migrate(this.props.position)} className={rev} alt={object.nombre}/>
			}
			else {
				return <img src={object.imgSrc} style={object.style} className={object.type} alt={object.type} />
			}
		} 
	}


getObstacle() {
		let obstacle = this.props.board.obstacleBoard[this.position[0]][this.position[1]]

		if (obstacle) {
			if (obstacle.description) {
				return <img src={obstacle.description.imgSrc} style={obstacle.description.style}/>
			}
		} 
	}
	render() {

		return (
		  <div className='square' 
		  	onClick={this.handleClick} 
				style={this.style}
				id = {this.position}

			>
			{this.getObstacle()}
			{this.getObject()}
		  </div>
		)
	}
}

export default Square